version: '2'
services:
  config-server:
    container_name: demo-app-001
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-app-001
    expose:
      - 8080
    ports:
      - 8080:8080