version: '2'
services:
  api-database:
    image: mongo:4.0.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  config-server:
    container_name: api-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: api-backend
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - api-database